defmodule TermigateWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :termigate

  # Static base for the session cookie store. The `:secure` and `:same_site`
  # attributes are resolved at runtime in `runtime_session/2` below so that
  # toggling `TERMIGATE_SECURE_COOKIES` on a release only requires a process
  # restart, not a rebuild. This base is still used by the LiveView /
  # UserSocket WebSocket connect_info — that path only *reads* the session
  # cookie during upgrade and is unaffected by `:secure` (which gates
  # Set-Cookie writes).
  @session_options [
    store: :cookie,
    key: "_termigate_key",
    signing_salt: "KIiTW2EZ",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [compress: true, connect_info: [:peer_data, session: @session_options]],
    longpoll: [connect_info: [:peer_data, session: @session_options]]

  socket "/socket", TermigateWeb.UserSocket,
    websocket: [
      compress: true,
      connect_info: [:peer_data, :x_headers, session: @session_options]
    ]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :termigate,
    gzip: not code_reloading?,
    only_matching: TermigateWeb.static_paths()

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug TermigateWeb.Plugs.RemoteIp
  plug TermigateWeb.Plugs.Cors
  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug :runtime_session
  plug TermigateWeb.Router

  @doc """
  Plug entry point that defers `Plug.Session` initialization until request
  time. The `:secure` flag is sourced from `:termigate, :secure_cookies` —
  set at runtime by `config/runtime.exs` from `TERMIGATE_SECURE_COOKIES` —
  and `:same_site` is tightened to `"Strict"` whenever Secure is on.
  """
  def runtime_session(conn, _opts) do
    Plug.Session.call(conn, Plug.Session.init(runtime_session_options()))
  end

  @doc """
  Builds session options at runtime by combining the static base (store,
  key, signing salt) with the application-env-driven `:secure` flag and
  the matching `:same_site` policy. Exposed for tests.
  """
  def runtime_session_options do
    secure = Application.get_env(:termigate, :secure_cookies, false)
    same_site = if secure, do: "Strict", else: "Lax"

    [
      store: :cookie,
      key: "_termigate_key",
      signing_salt: "KIiTW2EZ",
      same_site: same_site,
      secure: secure
    ]
  end
end
